apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}-grafana-datasource
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://thanos-query-http:10902
      access: proxy
      isDefault: true
