{{- if .Values.store.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  generation: 1
  name: {{ include "thanos.fullname" . }}-store
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: store
spec:
  groups:
  - name: thanos-store.rules
    rules:
    - alert: ThanosStoreGrpcErrorRate
      expr: rate(grpc_server_handled_total{grpc_code=~"Unknown|ResourceExhausted|Internal|Unavailable",job="thanos-store-http"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Store is returning Internal/Unavailable errors
        description: Long Term Storage Prometheus queries are failing
        severity: warning
    - alert: ThanosStoreBucketOperationsFailed
      expr: rate(thanos_objstore_bucket_operation_failures_total{job="thanos-store-http"}[5m]) > 0
      for: 5m
      annotations:
        summary: Thanos Store is failing to do bucket operations
        description: Long Term Storage Prometheus queries are failing
        severity: warning
    - alert: ThanosStoreIsNotRunning
      expr: up{job="thanos-store-http"} == 0 or absent({job="thanos-store-http"})
      for: 5m
      annotations:
        summary: Thanos Store is not running
        description: Long term storage queries will not work
        severity: critical
{{- end -}}
