prometheus-operator:
  prometheus:
    prometheusSpec:
      replicas: 2
      externalLabels:
        region: local
        replica: a
      thanos:
        objectStorageConfig:
          # this should be ${releaseName}-thanos-object-store
          name: thanos-thanos-object-store
          key: store.yaml

  grafana:
    envFromSecret: grafana-secrets
    env:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_USER: grafana
      GF_DATABASE_HOST: grafanadb-mysql.mysql.svc.cluster.local

query:
  replicaCount: 2
  logLevel: info

store:
  replicaCount: 2
