prometheus-operator:
  prometheus:
    prometheusSpec:
      replicas: 1
      retention: 4h
      image:
        tag: v2.10.0
      # this is needed to make prometheus-operator do the expected thing and
      # actually use servicemonitors and prometheusrules created 'from outside'
      # the helm chart.
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}
      ruleSelectorNilUsesHelmValues: false
      ruleNamespaceSelector: {}
      ruleSelector: {}
      thanos:
        tag: v0.4.0

  grafana:
    adminPassword: admin
    sidecar:
      datasources:
        enabled: true
        defaultDatasourceEnabled: false
        label: grafana_datasource
      dashboards:
        enabled: true
        label: grafana_dashboard

  prometheusOperator:
    image:
      tag: v0.30.0

image:
  repository: improbable/thanos
  tag: v0.4.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Thanos object storage configuration (Azure Blob, EWS S3, etc.)
# see ref: https://github.com/improbable-eng/thanos/blob/master/docs/storage.md
objectStorageConfig:
  enabled: false
  key: thanos.yaml
  name: thanos-objstore-config

# Thanos store configuration
store:
  enabled: true
  replicaCount: 1

  logLevel: debug

  # cert, key and ca are strings and can be overwritten using `helm install <chart> --set-file <key>=/path/to/file`
  tlsServer:
    enabled: false
    # certificate and key for server TLS
    cert: ""
    key: ""
    # CA to validate the remote client certificate
    ca: ""

  deployment:
    annotations: {}

  grpcService:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: ""
    annotations: {}

  httpService:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: ""
    annotations: {}

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Thanos query configuration
query:
  enabled: true
  replicaCount: 1
  logLevel: info
  # https://github.com/improbable-eng/thanos/issues/1015
  storeDNSResolver: miekgdns
  stores:
    - dnssrv+_grpc._tcp.thanos-store-grpc.thanos.svc.cluster.local
    - dnssrv+_grpc._tcp.thanos-sidecar-grpc.thanos.svc.cluster.local
  queryReplicaLabel: replica

  # cert, key and ca are strings and can be overwritten using `helm install <chart> --set-file <key>=/path/to/file`
  tlsClient:
    enabled: false
    # certificate and key for client side authentication to stores
    cert: ""
    key: ""
    # CA to validate the remote store certificate
    ca: ""
    # (optional) server name indication to the stores (ref: https://tools.ietf.org/html/rfc4366#section-3.1)
    serverName: ""

  # cert, key and ca are strings and can be overwritten using `helm install <chart> --set-file <key>=/path/to/file`
  tlsServer:
    enabled: false
    # certificate and key for server TLS
    cert: ""
    key: ""
    # CA to validate the remote client certificate
    ca: ""

  deployment:
    annotations: {}

  grpcService:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: ""
    annotations: {}

  httpService:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: ""
    annotations: {}

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Thanos compact configuration
compact:
  enabled: false
  replicaCount: 1

  syncDelay: 30m
  retentionResolutionRaw: 0d
  retentionResolution5m: 0d
  retentionResolution1h: 0d
  wait: true

  logLevel: debug

  deployment:
    annotations: {}

  httpService:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: ""
    annotations: {}

sidecar:
  httpService:
    enabled: true
    type: ClusterIP
    externalTrafficPolicy: ""
